fail_fast: false
repos:
repos:
  - repo: local
    hooks:
    - id: clang-format
      name: clang-format
      entry: clang-format
      language: system
      files: \.(c|cpp|h)$

  # - repo: https://github.com/pocc/pre-commit-hooks
  #   rev: master
  #   hooks:
  #     - id: cppcheck
  #       args: [--suppress=unusedStructMember]